/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_reclamation_client (void);
GtkWidget* create_gestion_reclamation_agent1 (void);
GtkWidget* create_recherche_rec_nour (void);
GtkWidget* create_historiq_reclamations (void);
GtkWidget* create_modif_recl (void);
GtkWidget* create_validation_ajout_rec (void);
GtkWidget* create_validation_modif_rec (void);
GtkWidget* create_validation_supp_rec (void);
