/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_reclamation_client (void)
{
  GtkWidget *fenetre_reclamation_client;
  GtkWidget *fixed1;
  GtkWidget *entryreclclient;
  GtkWidget *entry_numres_client;
  GtkWidget *entry_daterec;
  GtkWidget *numresclient;
  GtkWidget *daterec_client;
  GtkWidget *buttonhistorique;
  GtkWidget *image23;
  GtkWidget *buttonajouter;
  GtkWidget *image21;
  GtkWidget *buttonquitter;
  GtkWidget *image22;
  GtkWidget *historique;
  GtkWidget *ajouter;
  GtkWidget *quitter;
  GtkWidget *comboboxrec;

  fenetre_reclamation_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_reclamation_client), _("R\303\251clamation"));
  gtk_window_set_position (GTK_WINDOW (fenetre_reclamation_client), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (fenetre_reclamation_client), 200, 200);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_reclamation_client), fixed1);

  entryreclclient = gtk_entry_new ();
  gtk_widget_show (entryreclclient);
  gtk_fixed_put (GTK_FIXED (fixed1), entryreclclient, 96, 128);
  gtk_widget_set_size_request (entryreclclient, 272, 152);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryreclclient), 8226);

  entry_numres_client = gtk_entry_new ();
  gtk_widget_show (entry_numres_client);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_numres_client, 176, 16);
  gtk_widget_set_size_request (entry_numres_client, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numres_client), 8226);

  entry_daterec = gtk_entry_new ();
  gtk_widget_show (entry_daterec);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_daterec, 176, 48);
  gtk_widget_set_size_request (entry_daterec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_daterec), 8226);

  numresclient = gtk_label_new (_("Num de reservation :"));
  gtk_widget_show (numresclient);
  gtk_fixed_put (GTK_FIXED (fixed1), numresclient, 16, 16);
  gtk_widget_set_size_request (numresclient, 152, 24);

  daterec_client = gtk_label_new (_("Date de service :"));
  gtk_widget_show (daterec_client);
  gtk_fixed_put (GTK_FIXED (fixed1), daterec_client, 24, 48);
  gtk_widget_set_size_request (daterec_client, 144, 24);

  buttonhistorique = gtk_button_new ();
  gtk_widget_show (buttonhistorique);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonhistorique, 264, 288);
  gtk_widget_set_size_request (buttonhistorique, 48, 40);

  image23 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_container_add (GTK_CONTAINER (buttonhistorique), image23);

  buttonajouter = gtk_button_new ();
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajouter, 344, 288);
  gtk_widget_set_size_request (buttonajouter, 48, 40);

  image21 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (buttonajouter), image21);

  buttonquitter = gtk_button_new ();
  gtk_widget_show (buttonquitter);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonquitter, 408, 288);
  gtk_widget_set_size_request (buttonquitter, 48, 40);

  image22 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_container_add (GTK_CONTAINER (buttonquitter), image22);

  historique = gtk_label_new (_("historique"));
  gtk_widget_show (historique);
  gtk_fixed_put (GTK_FIXED (fixed1), historique, 248, 328);
  gtk_widget_set_size_request (historique, 88, 24);

  ajouter = gtk_label_new (_("ajouter"));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 344, 328);
  gtk_widget_set_size_request (ajouter, 48, 24);

  quitter = gtk_label_new (_("quitter"));
  gtk_widget_show (quitter);
  gtk_fixed_put (GTK_FIXED (fixed1), quitter, 408, 328);
  gtk_widget_set_size_request (quitter, 48, 24);

  comboboxrec = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxrec);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxrec, 104, 80);
  gtk_widget_set_size_request (comboboxrec, 240, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxrec), _("problemes_de_vol"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxrec), _("problemes_de_guide_touristique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxrec), _("problemes_des_services_hoteliers"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxrec), _("problemes_de_location_des_voitures"));

  g_signal_connect ((gpointer) buttonhistorique, "clicked",
                    G_CALLBACK (on_buttonhistorique_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajouter, "clicked",
                    G_CALLBACK (on_buttonajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonquitter, "clicked",
                    G_CALLBACK (on_buttonquitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_reclamation_client, fenetre_reclamation_client, "fenetre_reclamation_client");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, entryreclclient, "entryreclclient");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, entry_numres_client, "entry_numres_client");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, entry_daterec, "entry_daterec");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, numresclient, "numresclient");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, daterec_client, "daterec_client");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, buttonhistorique, "buttonhistorique");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, image23, "image23");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, image21, "image21");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, buttonquitter, "buttonquitter");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, image22, "image22");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, historique, "historique");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, quitter, "quitter");
  GLADE_HOOKUP_OBJECT (fenetre_reclamation_client, comboboxrec, "comboboxrec");

  return fenetre_reclamation_client;
}

GtkWidget*
create_gestion_reclamation_agent1 (void)
{
  GtkWidget *gestion_reclamation_agent1;
  GtkWidget *fixed4;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menu1;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem2;
  GtkWidget *menu2;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem3;
  GtkWidget *menu3;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *about1;
  GtkWidget *menubar2;
  GtkWidget *menuitem5;
  GtkWidget *menu5;
  GtkWidget *new2;
  GtkWidget *open2;
  GtkWidget *save2;
  GtkWidget *save_as2;
  GtkWidget *separatormenuitem2;
  GtkWidget *quit2;
  GtkWidget *menuitem6;
  GtkWidget *menu6;
  GtkWidget *cut2;
  GtkWidget *copy2;
  GtkWidget *paste2;
  GtkWidget *delete2;
  GtkWidget *menuitem7;
  GtkWidget *menu7;
  GtkWidget *menuitem8;
  GtkWidget *menu8;
  GtkWidget *about2;
  GtkWidget *button_afficher_tabrec;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *button_quitter_rec_agent;
  GtkWidget *image24;
  GtkWidget *afficher;
  GtkWidget *quitter;
  GtkWidget *chercher;
  GtkWidget *buttonchercher1_client;
  GtkWidget *image27;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *hbuttonbox1;
  GtkWidget *treeview_gestion_rec;
  GtkWidget *gestion_rec_agent;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  gestion_reclamation_agent1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_reclamation_agent1, 900, 600);
  gtk_window_set_title (GTK_WINDOW (gestion_reclamation_agent1), _("Gestion des r\303\251clamations"));
  gtk_window_set_position (GTK_WINDOW (gestion_reclamation_agent1), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (gestion_reclamation_agent1), fixed4);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_fixed_put (GTK_FIXED (fixed4), menubar1, 152, 72);
  gtk_widget_set_size_request (menubar1, 32, 24);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menu1 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menu1);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menu1), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menu1), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menu1), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menu1), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu1), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menu1), quit1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menu2 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menu2);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menu2), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menu2), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menu2), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menu2), delete1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menu3 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menu3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu4), about1);

  menubar2 = gtk_menu_bar_new ();
  gtk_widget_show (menubar2);
  gtk_fixed_put (GTK_FIXED (fixed4), menubar2, 112, 72);
  gtk_widget_set_size_request (menubar2, 32, 24);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem5);

  menu5 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menu5);

  new2 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new2);
  gtk_container_add (GTK_CONTAINER (menu5), new2);

  open2 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open2);
  gtk_container_add (GTK_CONTAINER (menu5), open2);

  save2 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save2);
  gtk_container_add (GTK_CONTAINER (menu5), save2);

  save_as2 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as2);
  gtk_container_add (GTK_CONTAINER (menu5), save_as2);

  separatormenuitem2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem2);
  gtk_container_add (GTK_CONTAINER (menu5), separatormenuitem2);
  gtk_widget_set_sensitive (separatormenuitem2, FALSE);

  quit2 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit2);
  gtk_container_add (GTK_CONTAINER (menu5), quit2);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem6);

  menu6 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menu6);

  cut2 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut2);
  gtk_container_add (GTK_CONTAINER (menu6), cut2);

  copy2 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy2);
  gtk_container_add (GTK_CONTAINER (menu6), copy2);

  paste2 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste2);
  gtk_container_add (GTK_CONTAINER (menu6), paste2);

  delete2 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete2);
  gtk_container_add (GTK_CONTAINER (menu6), delete2);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem7);

  menu7 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menu7);

  menuitem8 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem8);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem8);

  menu8 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem8), menu8);

  about2 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about2);
  gtk_container_add (GTK_CONTAINER (menu8), about2);

  button_afficher_tabrec = gtk_button_new ();
  gtk_widget_show (button_afficher_tabrec);
  gtk_fixed_put (GTK_FIXED (fixed4), button_afficher_tabrec, 760, 400);
  gtk_widget_set_size_request (button_afficher_tabrec, 48, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_afficher_tabrec), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  button_quitter_rec_agent = gtk_button_new ();
  gtk_widget_show (button_quitter_rec_agent);
  gtk_fixed_put (GTK_FIXED (fixed4), button_quitter_rec_agent, 696, 400);
  gtk_widget_set_size_request (button_quitter_rec_agent, 48, 40);

  image24 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_container_add (GTK_CONTAINER (button_quitter_rec_agent), image24);

  afficher = gtk_label_new (_("afficher"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed4), afficher, 752, 440);
  gtk_widget_set_size_request (afficher, 72, 32);

  quitter = gtk_label_new (_("quitter"));
  gtk_widget_show (quitter);
  gtk_fixed_put (GTK_FIXED (fixed4), quitter, 688, 440);
  gtk_widget_set_size_request (quitter, 65, 32);

  chercher = gtk_label_new (_("chercher"));
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed4), chercher, 608, 440);
  gtk_widget_set_size_request (chercher, 88, 32);

  buttonchercher1_client = gtk_button_new ();
  gtk_widget_show (buttonchercher1_client);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonchercher1_client, 624, 400);
  gtk_widget_set_size_request (buttonchercher1_client, 48, 40);

  image27 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (buttonchercher1_client), image27);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed4), notebook1, 8, 16);
  gtk_widget_set_size_request (notebook1, 850, 350);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);
  gtk_widget_set_size_request (fixed5, 800, 300);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed5), hbuttonbox1, 264, 200);
  gtk_widget_set_size_request (hbuttonbox1, 300, 29);

  treeview_gestion_rec = gtk_tree_view_new ();
  gtk_widget_show (treeview_gestion_rec);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview_gestion_rec, 32, 40);
  gtk_widget_set_size_request (treeview_gestion_rec, 800, 200);

  gestion_rec_agent = gtk_label_new (_("Gestion des r\303\251clamations"));
  gtk_widget_show (gestion_rec_agent);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), gestion_rec_agent);

  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) new2, "activate",
                    G_CALLBACK (on_new2_activate),
                    NULL);
  g_signal_connect ((gpointer) open2, "activate",
                    G_CALLBACK (on_open2_activate),
                    NULL);
  g_signal_connect ((gpointer) save2, "activate",
                    G_CALLBACK (on_save2_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as2, "activate",
                    G_CALLBACK (on_save_as2_activate),
                    NULL);
  g_signal_connect ((gpointer) quit2, "activate",
                    G_CALLBACK (on_quit2_activate),
                    NULL);
  g_signal_connect ((gpointer) cut2, "activate",
                    G_CALLBACK (on_cut2_activate),
                    NULL);
  g_signal_connect ((gpointer) copy2, "activate",
                    G_CALLBACK (on_copy2_activate),
                    NULL);
  g_signal_connect ((gpointer) paste2, "activate",
                    G_CALLBACK (on_paste2_activate),
                    NULL);
  g_signal_connect ((gpointer) delete2, "activate",
                    G_CALLBACK (on_delete2_activate),
                    NULL);
  g_signal_connect ((gpointer) about2, "activate",
                    G_CALLBACK (on_about2_activate),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_tabrec, "clicked",
                    G_CALLBACK (on_button_afficher_tabrec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_quitter_rec_agent, "clicked",
                    G_CALLBACK (on_button_quitter_rec_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonchercher1_client, "clicked",
                    G_CALLBACK (on_buttonchercher1_client_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_reclamation_agent1, gestion_reclamation_agent1, "gestion_reclamation_agent1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, new1, "new1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, open1, "open1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, save1, "save1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu3, "menu3");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, about1, "about1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menubar2, "menubar2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu5, "menu5");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, new2, "new2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, open2, "open2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, save2, "save2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, save_as2, "save_as2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, separatormenuitem2, "separatormenuitem2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, quit2, "quit2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu6, "menu6");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, cut2, "cut2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, copy2, "copy2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, paste2, "paste2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, delete2, "delete2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu7, "menu7");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menuitem8, "menuitem8");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, menu8, "menu8");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, about2, "about2");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, button_afficher_tabrec, "button_afficher_tabrec");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, image18, "image18");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, button_quitter_rec_agent, "button_quitter_rec_agent");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, image24, "image24");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, quitter, "quitter");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, buttonchercher1_client, "buttonchercher1_client");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, image27, "image27");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, treeview_gestion_rec, "treeview_gestion_rec");
  GLADE_HOOKUP_OBJECT (gestion_reclamation_agent1, gestion_rec_agent, "gestion_rec_agent");

  gtk_window_add_accel_group (GTK_WINDOW (gestion_reclamation_agent1), accel_group);

  return gestion_reclamation_agent1;
}

GtkWidget*
create_recherche_rec_nour (void)
{
  GtkWidget *recherche_rec_nour;
  GtkWidget *fixed14;
  GtkWidget *entryrecherche;
  GtkWidget *entryreclamation_agent;
  GtkWidget *cherchertreeview;
  GtkWidget *chercher;
  GtkWidget *buttonchercher2;
  GtkWidget *image19;
  GtkWidget *buttonsupprimer_rec_client;
  GtkWidget *image28;
  GtkWidget *labelsupprimer_rec;
  GtkWidget *labelretour_fen_gestagent;
  GtkWidget *buttonretour_gestrec_agent;
  GtkWidget *image33;

  recherche_rec_nour = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (recherche_rec_nour, 450, 300);
  gtk_window_set_title (GTK_WINDOW (recherche_rec_nour), _("Recherche des r\303\251clamations"));
  gtk_window_set_position (GTK_WINDOW (recherche_rec_nour), GTK_WIN_POS_CENTER);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (recherche_rec_nour), fixed14);

  entryrecherche = gtk_entry_new ();
  gtk_widget_show (entryrecherche);
  gtk_fixed_put (GTK_FIXED (fixed14), entryrecherche, 144, 40);
  gtk_widget_set_size_request (entryrecherche, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrecherche), 8226);

  entryreclamation_agent = gtk_entry_new ();
  gtk_widget_show (entryreclamation_agent);
  gtk_fixed_put (GTK_FIXED (fixed14), entryreclamation_agent, 112, 96);
  gtk_widget_set_size_request (entryreclamation_agent, 256, 128);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryreclamation_agent), 8226);

  cherchertreeview = gtk_label_new (_("Num_reservation"));
  gtk_widget_show (cherchertreeview);
  gtk_fixed_put (GTK_FIXED (fixed14), cherchertreeview, 144, 8);
  gtk_widget_set_size_request (cherchertreeview, 176, 24);

  chercher = gtk_label_new (_("chercher"));
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed14), chercher, 384, 264);
  gtk_widget_set_size_request (chercher, 64, 32);

  buttonchercher2 = gtk_button_new ();
  gtk_widget_show (buttonchercher2);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonchercher2, 392, 224);
  gtk_widget_set_size_request (buttonchercher2, 48, 40);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (buttonchercher2), image19);

  buttonsupprimer_rec_client = gtk_button_new ();
  gtk_widget_show (buttonsupprimer_rec_client);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonsupprimer_rec_client, 320, 224);
  gtk_widget_set_size_request (buttonsupprimer_rec_client, 48, 40);

  image28 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_container_add (GTK_CONTAINER (buttonsupprimer_rec_client), image28);

  labelsupprimer_rec = gtk_label_new (_("supprimer"));
  gtk_widget_show (labelsupprimer_rec);
  gtk_fixed_put (GTK_FIXED (fixed14), labelsupprimer_rec, 304, 264);
  gtk_widget_set_size_request (labelsupprimer_rec, 80, 32);

  labelretour_fen_gestagent = gtk_label_new (_("retour"));
  gtk_widget_show (labelretour_fen_gestagent);
  gtk_fixed_put (GTK_FIXED (fixed14), labelretour_fen_gestagent, 248, 264);
  gtk_widget_set_size_request (labelretour_fen_gestagent, 56, 32);

  buttonretour_gestrec_agent = gtk_button_new ();
  gtk_widget_show (buttonretour_gestrec_agent);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonretour_gestrec_agent, 248, 224);
  gtk_widget_set_size_request (buttonretour_gestrec_agent, 48, 40);

  image33 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_container_add (GTK_CONTAINER (buttonretour_gestrec_agent), image33);

  g_signal_connect ((gpointer) buttonchercher2, "clicked",
                    G_CALLBACK (on_buttonchercher2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimer_rec_client, "clicked",
                    G_CALLBACK (on_buttonsupprimer_rec_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretour_gestrec_agent, "clicked",
                    G_CALLBACK (on_buttonretour_gestrec_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche_rec_nour, recherche_rec_nour, "recherche_rec_nour");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, entryrecherche, "entryrecherche");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, entryreclamation_agent, "entryreclamation_agent");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, cherchertreeview, "cherchertreeview");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, buttonchercher2, "buttonchercher2");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, image19, "image19");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, buttonsupprimer_rec_client, "buttonsupprimer_rec_client");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, image28, "image28");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, labelsupprimer_rec, "labelsupprimer_rec");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, labelretour_fen_gestagent, "labelretour_fen_gestagent");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, buttonretour_gestrec_agent, "buttonretour_gestrec_agent");
  GLADE_HOOKUP_OBJECT (recherche_rec_nour, image33, "image33");

  return recherche_rec_nour;
}

GtkWidget*
create_historiq_reclamations (void)
{
  GtkWidget *historiq_reclamations;
  GtkWidget *fixed15;
  GtkWidget *label8;
  GtkWidget *rsfgbhngfh;
  GtkWidget *treeview_historiq_reclamations;
  GtkWidget *retour;
  GtkWidget *buttonmodif_rec;
  GtkWidget *image29;
  GtkWidget *modifrec_client;
  GtkWidget *button_retour_fenajout_recl;
  GtkWidget *image25;

  historiq_reclamations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (historiq_reclamations, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (historiq_reclamations), _("Historique des r\303\251clamations des clients"));
  gtk_window_set_position (GTK_WINDOW (historiq_reclamations), GTK_WIN_POS_CENTER);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (historiq_reclamations), fixed15);

  label8 = gtk_label_new ("");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed15), label8, 152, 24);
  gtk_widget_set_size_request (label8, 41, 17);

  rsfgbhngfh = gtk_label_new (_("afficher les reclamations"));
  gtk_widget_show (rsfgbhngfh);
  gtk_fixed_put (GTK_FIXED (fixed15), rsfgbhngfh, 152, 32);
  gtk_widget_set_size_request (rsfgbhngfh, 176, 24);

  treeview_historiq_reclamations = gtk_tree_view_new ();
  gtk_widget_show (treeview_historiq_reclamations);
  gtk_fixed_put (GTK_FIXED (fixed15), treeview_historiq_reclamations, 32, 72);
  gtk_widget_set_size_request (treeview_historiq_reclamations, 950, 550);

  retour = gtk_label_new (_("retour"));
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed15), retour, 840, 680);
  gtk_widget_set_size_request (retour, 64, 24);

  buttonmodif_rec = gtk_button_new ();
  gtk_widget_show (buttonmodif_rec);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonmodif_rec, 784, 640);
  gtk_widget_set_size_request (buttonmodif_rec, 48, 40);

  image29 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_container_add (GTK_CONTAINER (buttonmodif_rec), image29);

  modifrec_client = gtk_label_new (_("modifier"));
  gtk_widget_show (modifrec_client);
  gtk_fixed_put (GTK_FIXED (fixed15), modifrec_client, 784, 680);
  gtk_widget_set_size_request (modifrec_client, 57, 24);

  button_retour_fenajout_recl = gtk_button_new ();
  gtk_widget_show (button_retour_fenajout_recl);
  gtk_fixed_put (GTK_FIXED (fixed15), button_retour_fenajout_recl, 848, 640);
  gtk_widget_set_size_request (button_retour_fenajout_recl, 48, 40);

  image25 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_container_add (GTK_CONTAINER (button_retour_fenajout_recl), image25);

  g_signal_connect ((gpointer) buttonmodif_rec, "clicked",
                    G_CALLBACK (on_buttonmodif_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_fenajout_recl, "clicked",
                    G_CALLBACK (on_button_retour_fenajout_recl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (historiq_reclamations, historiq_reclamations, "historiq_reclamations");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, label8, "label8");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, rsfgbhngfh, "rsfgbhngfh");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, treeview_historiq_reclamations, "treeview_historiq_reclamations");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, retour, "retour");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, buttonmodif_rec, "buttonmodif_rec");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, image29, "image29");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, modifrec_client, "modifrec_client");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, button_retour_fenajout_recl, "button_retour_fenajout_recl");
  GLADE_HOOKUP_OBJECT (historiq_reclamations, image25, "image25");

  return historiq_reclamations;
}

GtkWidget*
create_modif_recl (void)
{
  GtkWidget *modif_recl;
  GtkWidget *fixed16;
  GtkWidget *entrynumres1;
  GtkWidget *entrynumres2;
  GtkWidget *entry_recente_rec;
  GtkWidget *entrytype_prob;
  GtkWidget *entrydate_rec_client;
  GtkWidget *chercherrec_client_nour;
  GtkWidget *button_cherchetmodif_rec;
  GtkWidget *image30;
  GtkWidget *cherche_recl2;
  GtkWidget *daterec1;
  GtkWidget *labeltype_prob;
  GtkWidget *reclamation1;
  GtkWidget *numres3;
  GtkWidget *valid_modif_rec;
  GtkWidget *retour_fenrecl;
  GtkWidget *button_retour_fenrecl;
  GtkWidget *image32;
  GtkWidget *buttonvaliser_modif_recl;
  GtkWidget *image31;

  modif_recl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modif_recl, 400, 500);
  gtk_window_set_title (GTK_WINDOW (modif_recl), _("modification_reclam_client"));
  gtk_window_set_position (GTK_WINDOW (modif_recl), GTK_WIN_POS_CENTER);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (modif_recl), fixed16);

  entrynumres1 = gtk_entry_new ();
  gtk_widget_show (entrynumres1);
  gtk_fixed_put (GTK_FIXED (fixed16), entrynumres1, 120, 40);
  gtk_widget_set_size_request (entrynumres1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumres1), 8226);

  entrynumres2 = gtk_entry_new ();
  gtk_widget_show (entrynumres2);
  gtk_fixed_put (GTK_FIXED (fixed16), entrynumres2, 224, 176);
  gtk_widget_set_size_request (entrynumres2, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumres2), 8226);

  entry_recente_rec = gtk_entry_new ();
  gtk_widget_show (entry_recente_rec);
  gtk_fixed_put (GTK_FIXED (fixed16), entry_recente_rec, 224, 216);
  gtk_widget_set_size_request (entry_recente_rec, 168, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recente_rec), 8226);

  entrytype_prob = gtk_entry_new ();
  gtk_widget_show (entrytype_prob);
  gtk_fixed_put (GTK_FIXED (fixed16), entrytype_prob, 224, 288);
  gtk_widget_set_size_request (entrytype_prob, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytype_prob), 8226);

  entrydate_rec_client = gtk_entry_new ();
  gtk_widget_show (entrydate_rec_client);
  gtk_fixed_put (GTK_FIXED (fixed16), entrydate_rec_client, 224, 336);
  gtk_widget_set_size_request (entrydate_rec_client, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydate_rec_client), 8226);

  chercherrec_client_nour = gtk_label_new (_("Num\303\251ro de r\303\251servation"));
  gtk_widget_show (chercherrec_client_nour);
  gtk_fixed_put (GTK_FIXED (fixed16), chercherrec_client_nour, 104, 8);
  gtk_widget_set_size_request (chercherrec_client_nour, 192, 32);

  button_cherchetmodif_rec = gtk_button_new ();
  gtk_widget_show (button_cherchetmodif_rec);
  gtk_fixed_put (GTK_FIXED (fixed16), button_cherchetmodif_rec, 176, 80);
  gtk_widget_set_size_request (button_cherchetmodif_rec, 48, 40);

  image30 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_container_add (GTK_CONTAINER (button_cherchetmodif_rec), image30);

  cherche_recl2 = gtk_label_new (_("chercher"));
  gtk_widget_show (cherche_recl2);
  gtk_fixed_put (GTK_FIXED (fixed16), cherche_recl2, 168, 120);
  gtk_widget_set_size_request (cherche_recl2, 65, 24);

  daterec1 = gtk_label_new (_("Date de r\303\251clamation"));
  gtk_widget_show (daterec1);
  gtk_fixed_put (GTK_FIXED (fixed16), daterec1, 16, 336);
  gtk_widget_set_size_request (daterec1, 184, 24);

  labeltype_prob = gtk_label_new (_("Type de probl\303\251mes"));
  gtk_widget_show (labeltype_prob);
  gtk_fixed_put (GTK_FIXED (fixed16), labeltype_prob, 16, 288);
  gtk_widget_set_size_request (labeltype_prob, 184, 24);

  reclamation1 = gtk_label_new (_("votre r\303\251cente r\303\251clamation"));
  gtk_widget_show (reclamation1);
  gtk_fixed_put (GTK_FIXED (fixed16), reclamation1, 0, 232);
  gtk_widget_set_size_request (reclamation1, 208, 24);

  numres3 = gtk_label_new (_("votre num\303\251ro de r\303\251servation"));
  gtk_widget_show (numres3);
  gtk_fixed_put (GTK_FIXED (fixed16), numres3, 0, 176);
  gtk_widget_set_size_request (numres3, 216, 24);

  valid_modif_rec = gtk_label_new (_("valider"));
  gtk_widget_show (valid_modif_rec);
  gtk_fixed_put (GTK_FIXED (fixed16), valid_modif_rec, 264, 416);
  gtk_widget_set_size_request (valid_modif_rec, 57, 24);

  retour_fenrecl = gtk_label_new (_("retour"));
  gtk_widget_show (retour_fenrecl);
  gtk_fixed_put (GTK_FIXED (fixed16), retour_fenrecl, 328, 416);
  gtk_widget_set_size_request (retour_fenrecl, 56, 24);

  button_retour_fenrecl = gtk_button_new ();
  gtk_widget_show (button_retour_fenrecl);
  gtk_fixed_put (GTK_FIXED (fixed16), button_retour_fenrecl, 328, 376);
  gtk_widget_set_size_request (button_retour_fenrecl, 48, 40);

  image32 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_container_add (GTK_CONTAINER (button_retour_fenrecl), image32);

  buttonvaliser_modif_recl = gtk_button_new ();
  gtk_widget_show (buttonvaliser_modif_recl);
  gtk_fixed_put (GTK_FIXED (fixed16), buttonvaliser_modif_recl, 264, 376);
  gtk_widget_set_size_request (buttonvaliser_modif_recl, 48, 40);

  image31 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_container_add (GTK_CONTAINER (buttonvaliser_modif_recl), image31);

  g_signal_connect ((gpointer) button_cherchetmodif_rec, "clicked",
                    G_CALLBACK (on_button_cherchetmodif_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_fenrecl, "clicked",
                    G_CALLBACK (on_button_retour_fenrecl_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonvaliser_modif_recl, "clicked",
                    G_CALLBACK (on_buttonvaliser_modif_recl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_recl, modif_recl, "modif_recl");
  GLADE_HOOKUP_OBJECT (modif_recl, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (modif_recl, entrynumres1, "entrynumres1");
  GLADE_HOOKUP_OBJECT (modif_recl, entrynumres2, "entrynumres2");
  GLADE_HOOKUP_OBJECT (modif_recl, entry_recente_rec, "entry_recente_rec");
  GLADE_HOOKUP_OBJECT (modif_recl, entrytype_prob, "entrytype_prob");
  GLADE_HOOKUP_OBJECT (modif_recl, entrydate_rec_client, "entrydate_rec_client");
  GLADE_HOOKUP_OBJECT (modif_recl, chercherrec_client_nour, "chercherrec_client_nour");
  GLADE_HOOKUP_OBJECT (modif_recl, button_cherchetmodif_rec, "button_cherchetmodif_rec");
  GLADE_HOOKUP_OBJECT (modif_recl, image30, "image30");
  GLADE_HOOKUP_OBJECT (modif_recl, cherche_recl2, "cherche_recl2");
  GLADE_HOOKUP_OBJECT (modif_recl, daterec1, "daterec1");
  GLADE_HOOKUP_OBJECT (modif_recl, labeltype_prob, "labeltype_prob");
  GLADE_HOOKUP_OBJECT (modif_recl, reclamation1, "reclamation1");
  GLADE_HOOKUP_OBJECT (modif_recl, numres3, "numres3");
  GLADE_HOOKUP_OBJECT (modif_recl, valid_modif_rec, "valid_modif_rec");
  GLADE_HOOKUP_OBJECT (modif_recl, retour_fenrecl, "retour_fenrecl");
  GLADE_HOOKUP_OBJECT (modif_recl, button_retour_fenrecl, "button_retour_fenrecl");
  GLADE_HOOKUP_OBJECT (modif_recl, image32, "image32");
  GLADE_HOOKUP_OBJECT (modif_recl, buttonvaliser_modif_recl, "buttonvaliser_modif_recl");
  GLADE_HOOKUP_OBJECT (modif_recl, image31, "image31");

  return modif_recl;
}

GtkWidget*
create_validation_ajout_rec (void)
{
  GtkWidget *validation_ajout_rec;
  GtkWidget *fixed17;
  GtkWidget *labelvalid_ajoutrec;
  GtkWidget *buttonvalid_ajoutrec;
  GtkWidget *image34;

  validation_ajout_rec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (validation_ajout_rec, 300, 100);
  gtk_window_set_title (GTK_WINDOW (validation_ajout_rec), _("succ\303\251s !"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (validation_ajout_rec), fixed17);

  labelvalid_ajoutrec = gtk_label_new (_("votre r\303\251clamation a \303\251t\303\251 bien envoy\303\251e !!"));
  gtk_widget_show (labelvalid_ajoutrec);
  gtk_fixed_put (GTK_FIXED (fixed17), labelvalid_ajoutrec, 16, 8);
  gtk_widget_set_size_request (labelvalid_ajoutrec, 272, 32);

  buttonvalid_ajoutrec = gtk_button_new ();
  gtk_widget_show (buttonvalid_ajoutrec);
  gtk_fixed_put (GTK_FIXED (fixed17), buttonvalid_ajoutrec, 120, 48);
  gtk_widget_set_size_request (buttonvalid_ajoutrec, 48, 40);

  image34 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_container_add (GTK_CONTAINER (buttonvalid_ajoutrec), image34);

  g_signal_connect ((gpointer) buttonvalid_ajoutrec, "clicked",
                    G_CALLBACK (on_buttonvalid_ajoutrec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (validation_ajout_rec, validation_ajout_rec, "validation_ajout_rec");
  GLADE_HOOKUP_OBJECT (validation_ajout_rec, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (validation_ajout_rec, labelvalid_ajoutrec, "labelvalid_ajoutrec");
  GLADE_HOOKUP_OBJECT (validation_ajout_rec, buttonvalid_ajoutrec, "buttonvalid_ajoutrec");
  GLADE_HOOKUP_OBJECT (validation_ajout_rec, image34, "image34");

  return validation_ajout_rec;
}

GtkWidget*
create_validation_modif_rec (void)
{
  GtkWidget *validation_modif_rec;
  GtkWidget *fixed18;
  GtkWidget *labelvalid_modifrec;
  GtkWidget *buttonvalid_modifrec;
  GtkWidget *image35;

  validation_modif_rec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (validation_modif_rec, 300, 100);
  gtk_window_set_title (GTK_WINDOW (validation_modif_rec), _("succ\303\251s !"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (validation_modif_rec), fixed18);

  labelvalid_modifrec = gtk_label_new (_("votre r\303\251clamation a \303\251t\303\251 bien modifi\303\251e !!"));
  gtk_widget_show (labelvalid_modifrec);
  gtk_fixed_put (GTK_FIXED (fixed18), labelvalid_modifrec, 16, 8);
  gtk_widget_set_size_request (labelvalid_modifrec, 272, 40);

  buttonvalid_modifrec = gtk_button_new ();
  gtk_widget_show (buttonvalid_modifrec);
  gtk_fixed_put (GTK_FIXED (fixed18), buttonvalid_modifrec, 128, 48);
  gtk_widget_set_size_request (buttonvalid_modifrec, 48, 40);

  image35 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_container_add (GTK_CONTAINER (buttonvalid_modifrec), image35);

  g_signal_connect ((gpointer) buttonvalid_modifrec, "clicked",
                    G_CALLBACK (on_buttonvalid_modifrec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (validation_modif_rec, validation_modif_rec, "validation_modif_rec");
  GLADE_HOOKUP_OBJECT (validation_modif_rec, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (validation_modif_rec, labelvalid_modifrec, "labelvalid_modifrec");
  GLADE_HOOKUP_OBJECT (validation_modif_rec, buttonvalid_modifrec, "buttonvalid_modifrec");
  GLADE_HOOKUP_OBJECT (validation_modif_rec, image35, "image35");

  return validation_modif_rec;
}

GtkWidget*
create_validation_supp_rec (void)
{
  GtkWidget *validation_supp_rec;
  GtkWidget *fixed19;
  GtkWidget *label9;
  GtkWidget *buttonvalid_supprec;
  GtkWidget *image36;

  validation_supp_rec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (validation_supp_rec, 300, 100);
  gtk_window_set_title (GTK_WINDOW (validation_supp_rec), _("succ\303\251s !"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (validation_supp_rec), fixed19);

  label9 = gtk_label_new (_("votre r\303\251clamation a \303\251t\303\251 supprim\303\251e\n                      avec succ\303\251s !!"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed19), label9, 16, 8);
  gtk_widget_set_size_request (label9, 272, 40);

  buttonvalid_supprec = gtk_button_new ();
  gtk_widget_show (buttonvalid_supprec);
  gtk_fixed_put (GTK_FIXED (fixed19), buttonvalid_supprec, 120, 56);
  gtk_widget_set_size_request (buttonvalid_supprec, 48, 40);

  image36 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_container_add (GTK_CONTAINER (buttonvalid_supprec), image36);

  g_signal_connect ((gpointer) buttonvalid_supprec, "clicked",
                    G_CALLBACK (on_buttonvalid_supprec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (validation_supp_rec, validation_supp_rec, "validation_supp_rec");
  GLADE_HOOKUP_OBJECT (validation_supp_rec, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (validation_supp_rec, label9, "label9");
  GLADE_HOOKUP_OBJECT (validation_supp_rec, buttonvalid_supprec, "buttonvalid_supprec");
  GLADE_HOOKUP_OBJECT (validation_supp_rec, image36, "image36");

  return validation_supp_rec;
}

